version: 1
disable_existing_loggers: True

formatters:
    standard:
        format: "%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)s - %(funcName)8s() ] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        formatter: standard
        level: DEBUG
        stream: ext://sys.stdout

loggers:
    massox:
        level: INFO
        propagate: no
        handlers: [console, debug_rotating_file_handler, error_file_handler]

root:
    level: WARNING
    handlers: [console]